
        NATIVE_FUNCTIONPOW "POW";
        NATIVE_FUNCTIONFLOOR "FLOOR";
        NATIVE_FUNCTIONCEILING "CEILING";
        NATIVE_FUNCTIONINT "INT";
        NATIVE_FUNCTIONFLOAT "FLOAT";

        NATIVE_FUNCTION"?"; "?";
        NATIVE_FUNCTION"!?"; "!?";
        NATIVE_FUNCTION"^"; "^";

        NATIVE_FUNCTIONLIST_MIN "LIST_MIN";
        NATIVE_FUNCTIONLIST_MAX "LIST_MAX";
        NATIVE_FUNCTIONLIST_ALL "LIST_ALL";
        NATIVE_FUNCTIONLIST_COUNT "LIST_COUNT";
        NATIVE_FUNCTIONLIST_VALUE "LIST_VALUE";
        NATIVE_FUNCTIONLIST_INVERT "LIST_INVERT";