name: ci

on:
  push:
    branches:
      - 'main'
      - 'wip-networking'

jobs:
  linux-server:
    runs-on: ubuntu-latest
    environment: main
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build code
        run: |
          cd ./cicd/linux
          sudo ./build.sh
      -
        name: Build image and push
        uses: docker/build-push-action@v3
        with:
          file: ./cicd/linux/Dockerfile
          push: true
          tags: erinmaus/itsyrealm:latest
      -
        name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: itsyrealm
          path: |
            love.AppImage
            settings.cfg
            itsyrealm.love
