name: windows

on:
  push:
    branches:
      - 'master'

jobs:
  windows:
    runs-on: windows-2022
    environment: main
    defaults:
      run:
        shell: msys2 {0}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        uses: abel0b/setup-premake@v2.2
        with:
          version: "5.0.0-beta2"
      -
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-make
      -
        name: Build code
        run: |
          cd ./cicd/windows
          ./build.sh
      -
        name: Artifact
        uses: actions/upload-artifact@v2
        with:
          name: itsyrealm
          path: |
            cicd/windows/love.
            cicd/windows/settings.cfg
            cicd/windows/itsyrealm.love
